export enum configEnvKeys {
  port = 'PORT',
  nodeEnv = 'NODE_ENV',
  isProduction = 'isProduction',
  emailAddressApp = 'emailAddressApp',
  emailPasswordApp = 'emailPasswordApp',
  jwtAccessSecret = 'JWT_ACCESS_SECRET',
  jwtRefreshSecret = 'JWT_REFRESH_SECRET',
  accessTokenExpired = 'accessTokenExpired',
  refreshTokenExpired = 'refreshTokenExpired',
  mongoURI = 'mongoURI',
  mongoDBName = 'mongoDBName',
  adminLogin = 'adminLogin',
  adminPassword = 'adminPassword',
}
